import { GroupBadgeData } from "@pixel63/events";
import { GroupBadgeSymbolData } from "@pixel63/events/build/Groups/GroupBadgeData";
import DialogButton from "@UserInterface/Common/Dialog/Components/Button/DialogButton";
import FlexLayout from "@UserInterface/Common/Layouts/FlexLayout";
import GroupBadgeImage from "@UserInterface/Components/Groups/GroupBadgeImage";
import GroupBadgePosition from "@UserInterface/Components/Groups/Editor/GroupBadgePosition";
import GroupBadgeColor from "@UserInterface/Components/Groups/Editor/GroupBadgeColor";

export type GroupBadgeSymbolEditorProps = {
    data?: GroupBadgeSymbolData;
    onChange: (data: GroupBadgeSymbolData) => void;
    onSymbolChange: () => void;
};

export default function GroupBadgeSymbolEditor({ data, onChange, onSymbolChange }: GroupBadgeSymbolEditorProps) {
    return (
        <FlexLayout direction="row" justify="space-between" style={{
            background: "#BDBAA2",
            borderRadius: 3,
            padding: 3,
        }}>
            <div style={{ flex: 1 }}>
                <DialogButton style={{
                    aspectRatio: 1,
                    height: 44,
                }} contentStyle={{
                    padding: 0,
                    overflow: "visible"
                }} onClick={onSymbolChange}>
                    <GroupBadgeImage data={GroupBadgeData.create({
                        symbol1: data
                    })}/>
                </DialogButton>
            </div>

            <div style={{ flex: 1 }}>
                <GroupBadgePosition position={data?.position} onChange={(position) => onChange(GroupBadgeSymbolData.create({
                    ...data,
                    position
                }))}/>
            </div>

            <b style={{ flex: 2 }}>
                <GroupBadgeColor color={data?.color} onChange={(color) => onChange(GroupBadgeSymbolData.create({
                    ...data,
                    color
                }))}/>
            </b>
        </FlexLayout>
    );
}

export const groupBadgeSymbols = [
    "badgepart_symbol_0",
    "badgepart_symbol_1",
    "badgepart_symbol_2",
    "badgepart_symbol_3",
    "badgepart_symbol_4",
    "badgepart_symbol_5",
    "badgepart_symbol_6",
    "badgepart_symbol_7",
    "badgepart_symbol_8",
    "badgepart_symbol_9",
    "badgepart_symbol_a",
    "badgepart_symbol_alligator",
    "badgepart_symbol_americanfootball_part1",
    "badgepart_symbol_americanfootball_part2",
    "badgepart_symbol_arrowbig_up",
    "badgepart_symbol_arrow_down",
    "badgepart_symbol_arrow_left",
    "badgepart_symbol_arrow_right",
    "badgepart_symbol_arrow_up",
    "badgepart_symbol_award_part1",
    "badgepart_symbol_award_part2",
    "badgepart_symbol_axe_part1",
    "badgepart_symbol_axe_part2",
    "badgepart_symbol_b",
    "badgepart_symbol_background_1",
    "badgepart_symbol_background_2",
    "badgepart_symbol_background_3_part1",
    "badgepart_symbol_background_3_part2",
    "badgepart_symbol_ball_1_part1",
    "badgepart_symbol_ball_1_part2",
    "badgepart_symbol_ball_2_part1",
    "badgepart_symbol_ball_2_part2",
    "badgepart_symbol_bananapeel",
    "badgepart_symbol_battleball",
    "badgepart_symbol_biohazard",
    "badgepart_symbol_bird",
    "badgepart_symbol_bishop",
    "badgepart_symbol_bobba",
    "badgepart_symbol_bomb_part1",
    "badgepart_symbol_bomb_part2",
    "badgepart_symbol_bow",
    "badgepart_symbol_box_1",
    "badgepart_symbol_box_2",
    "badgepart_symbol_bug_part1",
    "badgepart_symbol_bug_part2",
    "badgepart_symbol_bunting_1",
    "badgepart_symbol_bunting_2",
    "badgepart_symbol_butterfly_part1",
    "badgepart_symbol_butterfly_part2",
    "badgepart_symbol_c",
    "badgepart_symbol_capsbig_part1",
    "badgepart_symbol_capsbig_part2",
    "badgepart_symbol_capssmall_part1",
    "badgepart_symbol_capssmall_part2",
    "badgepart_symbol_cloud",
    "badgepart_symbol_coalion",
    "badgepart_symbol_cocoamug",
    "badgepart_symbol_cowskull_part1",
    "badgepart_symbol_cowskull_part2",
    "badgepart_symbol_credit_part1",
    "badgepart_symbol_credit_part2",
    "badgepart_symbol_cross",
    "badgepart_symbol_crown_part1",
    "badgepart_symbol_crown_part2",
    "badgepart_symbol_d",
    "badgepart_symbol_dashflag",
    "badgepart_symbol_diamond",
    "badgepart_symbol_diamondring_part1",
    "badgepart_symbol_diamondring_part2",
    "badgepart_symbol_diamsmall",
    "badgepart_symbol_diamsmall2",
    "badgepart_symbol_diploma_part1",
    "badgepart_symbol_diploma_part2",
    "badgepart_symbol_discoball_part1",
    "badgepart_symbol_discoball_part2",
    "badgepart_symbol_dog",
    "badgepart_symbol_drop",
    "badgepart_symbol_e",
    "badgepart_symbol_electricguitarh_part1",
    "badgepart_symbol_electricguitarh_part2",
    "badgepart_symbol_electricguitarv_part1",
    "badgepart_symbol_electricguitarv_part2",
    "badgepart_symbol_eyeball_part1",
    "badgepart_symbol_eyeball_part2",
    "badgepart_symbol_f",
    "badgepart_symbol_film",
    "badgepart_symbol_fingersheavy",
    "badgepart_symbol_fingersv",
    "badgepart_symbol_fist",
    "badgepart_symbol_flame_1",
    "badgepart_symbol_flame_2",
    "badgepart_symbol_flame_part1",
    "badgepart_symbol_flame_part2",
    "badgepart_symbol_flash",
    "badgepart_symbol_flower_1_part1",
    "badgepart_symbol_flower_1_part2",
    "badgepart_symbol_flower_2",
    "badgepart_symbol_flower_3",
    "badgepart_symbol_flower_4",
    "badgepart_symbol_football",
    "badgepart_symbol_g",
    "badgepart_symbol_gamepad",
    "badgepart_symbol_gem1_part1",
    "badgepart_symbol_gem1_part2",
    "badgepart_symbol_gem2_part1",
    "badgepart_symbol_gem2_part2",
    "badgepart_symbol_gem3_part1",
    "badgepart_symbol_gem3_part2",
    "badgepart_symbol_gtr_part1",
    "badgepart_symbol_gtr_part2",
    "badgepart_symbol_h",
    "badgepart_symbol_hat",
    "badgepart_symbol_hawk",
    "badgepart_symbol_hc_part1",
    "badgepart_symbol_hc_part2",
    "badgepart_symbol_hearts_down",
    "badgepart_symbol_hearts_up",
    "badgepart_symbol_heart_1_part1",
    "badgepart_symbol_heart_1_part2",
    "badgepart_symbol_heart_2_part1",
    "badgepart_symbol_heart_2_part2",
    "badgepart_symbol_horseshoe",
    "badgepart_symbol_i",
    "badgepart_symbol_inksplatter",
    "badgepart_symbol_j",
    "badgepart_symbol_jingjang_part1",
    "badgepart_symbol_jingjang_part2",
    "badgepart_symbol_k",
    "badgepart_symbol_l",
    "badgepart_symbol_leaf",
    "badgepart_symbol_lips_part1",
    "badgepart_symbol_lips_part2",
    "badgepart_symbol_m",
    "badgepart_symbol_micstand",
    "badgepart_symbol_mirror_part1",
    "badgepart_symbol_mirror_part2",
    "badgepart_symbol_monkeywrench",
    "badgepart_symbol_n",
    "badgepart_symbol_note",
    "badgepart_symbol_note1",
    "badgepart_symbol_note2",
    "badgepart_symbol_note3",
    "badgepart_symbol_nursecross",
    "badgepart_symbol_o",
    "badgepart_symbol_oval_part1",
    "badgepart_symbol_oval_part2",
    "badgepart_symbol_p",
    "badgepart_symbol_pawprint",
    "badgepart_symbol_peace",
    "badgepart_symbol_pencil_part1",
    "badgepart_symbol_pencil_part2",
    "badgepart_symbol_pixel_part1",
    "badgepart_symbol_pixel_part2",
    "badgepart_symbol_planet_part1",
    "badgepart_symbol_planet_part2",
    "badgepart_symbol_q",
    "badgepart_symbol_queen",
    "badgepart_symbol_r",
    "badgepart_symbol_rainbow_part1",
    "badgepart_symbol_rainbow_part2",
    "badgepart_symbol_rock",
    "badgepart_symbol_rook",
    "badgepart_symbol_rosete",
    "badgepart_symbol_s",
    "badgepart_symbol_screw",
    "badgepart_symbol_shape",
    "badgepart_symbol_skate",
    "badgepart_symbol_smallring_part1",
    "badgepart_symbol_smallring_part2",
    "badgepart_symbol_snowstorm_part1",
    "badgepart_symbol_snowstorm_part2",
    "badgepart_symbol_sphere",
    "badgepart_symbol_spraycan_part1",
    "badgepart_symbol_spraycan_part2",
    "badgepart_symbol_stars1",
    "badgepart_symbol_stars2",
    "badgepart_symbol_stars3",
    "badgepart_symbol_stars4",
    "badgepart_symbol_stars5",
    "badgepart_symbol_star_1",
    "badgepart_symbol_star_2",
    "badgepart_symbol_stickL_part1",
    "badgepart_symbol_stickL_part2",
    "badgepart_symbol_stickR_part1",
    "badgepart_symbol_stickR_part2",
    "badgepart_symbol_sword_1_part1",
    "badgepart_symbol_sword_1_part2",
    "badgepart_symbol_sword_2_part1",
    "badgepart_symbol_sword_2_part2",
    "badgepart_symbol_sword_3_part1",
    "badgepart_symbol_sword_3_part2",
    "badgepart_symbol_t",
    "badgepart_symbol_u",
    "badgepart_symbol_v",
    "badgepart_symbol_vip_part1",
    "badgepart_symbol_vip_part2",
    "badgepart_symbol_w",
    "badgepart_symbol_waterdrop_part1",
    "badgepart_symbol_waterdrop_part2",
    "badgepart_symbol_wings_1",
    "badgepart_symbol_wings_2",
    "badgepart_symbol_wolverine",
    "badgepart_symbol_x",
    "badgepart_symbol_y",
    "badgepart_symbol_z"
];
