name: Build game package

on:
  workflow_run:
    workflows:
      - Generate events
      - Build shared package
    types:
      - completed

jobs:
  build-game-package:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download generated events
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: generate-events.yml
          workflow_conclusion: success
          name: generated-events
          path: packages/events/build/

      - name: Download built shared package
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-shared-package.yml
          workflow_conclusion: success
          name: shared-package
          path: packages/shared/build/

      - name: Install dependencies
        working-directory: packages/game
        run: npm ci

      - name: Build package
        working-directory: packages/game
        run: npm run build
