name: Build server package

on:
  workflow_call:

jobs:
  build-server-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download generated events
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: generate-events.yml
          workflow_conclusion: success
          name: generated-events
          path: packages/events/build/

      - name: Download built shared package
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-shared-package.yml
          workflow_conclusion: success
          name: shared-package
          path: packages/shared/build/

      - name: Install dependencies
        working-directory: packages/server
        run: npm ci

      - name: Build package
        working-directory: packages/server
        run: npm run build
