name: Pull request

on:
  pull_request:

jobs:
  generate-events:
    name: Generate events
    uses: ./.github/workflows/generate-events.yml

  build-shared-package:
    name: Build shared package
    uses: ./.github/workflows/build-shared-package.yml
    needs:
      - generate-events

  build-server-package:
    name: Build server package
    uses: ./.github/workflows/build-server-package.yml
    needs:
      - generate-events
      - build-shared-package

  build-game-package:
    name: Build game package
    uses: ./.github/workflows/build-game-package.yml
    needs:
      - generate-events
      - build-shared-package